_wdt:
    resource: /symfony/web-profiler-bundle/config/routing/wdt.xml
    prefix:   /_wdt

_profiler:
    resource: /symfony/web-profiler-bundle/config/routing/profiler.xml
    prefix:   /_profiler

_configurator:
    resource: /sensio/distribution-bundle/config/routing/webconfigurator.xml
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: /acme/demo-bundle/config/routing.yml
